GET http://localhost:8080/users/api/contact/

####
PUT http://localhost:8080/users/api/userupdate/68cd53334e66cad470b4e9e0
Content-Type: application/json

{
  "firstName": "Lahor",
  "lastName": "edddddddddd",
  "email": "john@example.com",
  "favoriteColor": "Blue",
  "birthday": "2000-01-01"
}

####
DELETE  http://localhost:8080/users/api/userdelete/68cab9668db660e05e7b401d
